site_name: "Nextflow & Freyja Tutorial"
theme:
  name: material
  features:
    - content.code.copy  # Enables the copy button for code blocks
    - navigation.footer  # Enables Previous & Next buttons
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


# navigation list 
nav:
  - Home: index.md
  - Environment setup:
      - Local installation: environment_setup.md
  - Nextflow Basics: 
      - Overview: nextflow_overview.md
      - Channels: channels.md
      - Processes: processes.md
      - Operators: operators.md
      - Workflows: workflows.md
  - Freyja Basics: freyja_basics.md
  - Building Nextflow Pipeline:
      - Overview: pipeline_overview.md
      - Project Setup: project_setup.md
      - Creating Modules:
          - Modules Overview: module_overview.md
          - Variant Module : variant.md
          - Demix Module: demix.md
      - Connecting the Pieces: connect_the_pieces.md
      - Running the Pipeline: running_pipeline.md
  - Customizing Parameters: customizing_parameters.md
  - Parallel Execution: parallel_execution.md
  - Containers & Reproducibility: containers_reproducibility.md
  - Best Practices: best_practices.md
 
markdown_extensions:
  - admonition             # Enables admonitions like notes, warnings, tips, etc !!! note/warning/tip
  - pymdownx.details       # Allows collapsible admonitions (click to expand) use ??? e.g ??? tip "click to expand"
  - pymdownx.superfences   # Enables nested code blocks inside admonitions
